### PR TITLE
added a new fish with a dialog button

### PR DESCRIPTION
**Pull request by archeni**
*added a new fish with a dialog button

### CODE REVIEW

**Comment by ghost** [comment]
works for me! approved!

**Review by iparkerhodge — APPROVED** [review]
👍 
fish appears and dialog works

looks good

**Review by ghost — APPROVED** [review]
looks good! approved

**Review by iparkerhodge — CHANGES_REQUESTED** [review]
👍 all the fish appear
👎 Dolly Purrton dialog box does not work

**Review by ygitore — COMMENTED** [review]
👍 dialog box is working. Image and name of fish displayed correctly

**Review by iparkerhodge — APPROVED** [review]
👍 Dolly dialog works now

everything seems good

**Pull request merged**
