### PR TITLE
Added Great White shark aka "Quint"

### PR DESCRIPTION
**Pull request by ghost**
Changes - 
Added great white shark info and javascript button to show info

Test - 
Make sure great white shark info shows on the site
Make sure the button works and shows info correctly

### CODE REVIEW

**Review by archeni — APPROVED** [review]
It works. gj

**Comment by iparkerhodge** [comment]
Quint appears and dialog works

**Review by ygitore — APPROVED** [review]
👍 Good job!

**Review by archeni — APPROVED** [review]
👍

**Pull request merged**
